//! Data-transfer objects shared between the Tauri backend and the TS client.
//! TypeScript is generated by the `gen-types` bin (feature `ts`); never hand-mirror these.

use serde::{Deserialize, Serialize};

#[cfg(feature = "ts")]
use ts_rs::TS;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct Workspace {
    pub id: String,
    pub name: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct CreateWorkspace {
    pub name: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct TeamMember {
    pub role: String,
    pub provider: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct Team {
    pub id: String,
    pub workspace_id: String,
    pub name: String,
    pub problem: String,
    pub members: Vec<TeamMember>,
    pub capabilities: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct CreateTeam {
    pub workspace_id: String,
    pub name: String,
    pub problem: String,
    pub auto: bool,
    pub members: Vec<TeamMember>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct RunStep {
    pub member_role: String,
    pub detail: String,
    pub status: String, // "running"|"done"|"error"
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct TeamRun {
    pub team_id: String,
    pub task: String,
    pub steps: Vec<RunStep>,
    pub result: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct Schedule {
    pub id: String,
    pub workspace_id: String,
    pub target: String,
    pub cadence: String,
    pub next_run: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct CreateSchedule {
    pub workspace_id: String,
    pub target: String,
    pub cadence: String,
    pub next_run: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct SearchHit {
    pub kind: String,
    pub id: String,
    pub title: String,
    pub snippet: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct Report {
    pub provider: String,
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct CrossVerify {
    pub reports: Vec<Report>,
    pub summary: String,
}

/// Wire event streamed from an agent to the stage. Mirrors the frontend
/// `StageEvent` union (`apps/desktop/src/engine/StageEngine.ts`); `tauriEngine`
/// maps this onto it. Internally tagged on `kind` so the TS side is a plain
/// discriminated union.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "ts", derive(TS))]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum StreamEvent {
    Token {
        text: String,
    },
    Tool {
        id: String,
        name: String,
        /// "running" | "done" | "error"
        status: String,
        detail: Option<String>,
    },
    Done,
    Error {
        message: String,
    },
}
