//! Data-transfer objects shared between the Tauri backend and the TS client.
//! TypeScript is generated by the `gen-types` bin (feature `ts`); never hand-mirror these.

use serde::{Deserialize, Serialize};

#[cfg(feature = "ts")]
use ts_rs::TS;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct Workspace {
    pub id: String,
    pub name: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts", derive(TS))]
pub struct CreateWorkspace {
    pub name: String,
    pub description: String,
}
